### ISSUE TITLE
fix plotly margin falling off

### ISSUE THREAD

**Issue by dmuijen** [dmuijen/PBR32803_qtl#3]
p$layout$margin$b <- p$layout$margin$b + 50 ## Rs, see https://github.com/ropensci/plotly/issues/512

**Comment by dnieuw** [comment]
Fixed by adding 10 px to the left margin:

```
p <- ggplot(p)
p$x$layout$margin$l <- p$x$layout$margin$l + 10
```
Need to add $x or [[1]] to the answer in https://github.com/ropensci/plotly/issues/512
